### ISSUE TITLE
collect to

### ISSUE THREAD

**Issue by velocityzen** [terkelg/facon#2]
Hey, great little lib. Love it.

What do you think about renaming `assign` option in `to`? It looks more comprehensive:

```js
view.collect({ assign: this }); 
//vs
view.collect({ to: this });
```

Thank you!

**Comment by mikehwagz** [comment]
I like this idea because it reads more naturally in english.

Guess you'd save a few bytes as well which never hurts! 😂

**Comment by terkelg** [comment]
Good idea!

**Comment by terkelg** [comment]
Awesome - It's published in the new release: https://github.com/terkelg/facon/releases/tag/v2.0.0
